USE [master]
GO

/****** Object:  Database [ReadingXML]    Script Date: 11/27/2016 16:06:02 ******/
CREATE DATABASE [ReadingXML] ON  PRIMARY 
( NAME = N'ReadingXML', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ReadingXML.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ReadingXML_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ReadingXML_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ReadingXML] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ReadingXML].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ReadingXML] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ReadingXML] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ReadingXML] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ReadingXML] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ReadingXML] SET ARITHABORT OFF 
GO

ALTER DATABASE [ReadingXML] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ReadingXML] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ReadingXML] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ReadingXML] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ReadingXML] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ReadingXML] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ReadingXML] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ReadingXML] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ReadingXML] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ReadingXML] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ReadingXML] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ReadingXML] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ReadingXML] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ReadingXML] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ReadingXML] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ReadingXML] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ReadingXML] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ReadingXML] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ReadingXML] SET  READ_WRITE 
GO

ALTER DATABASE [ReadingXML] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ReadingXML] SET  MULTI_USER 
GO

ALTER DATABASE [ReadingXML] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ReadingXML] SET DB_CHAINING OFF 
GO


